spring:
  application:
    name: organizationservice # 유레카에 등록할 서비스의 논리 이름
  profiles:
    active:
      default
  cloud:
    config:
      enabled: true

eureka:
  instance:
    preferIpAddress: true # 서비스 이름 대신 서비스 IP 주소 등록
  client:
    registerWithEureka: true # 유레카에 서비스 등록
    fetchRegistry: true # 유레카 서비스 위치
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/ # 레지스트리 사본을 로컬로 가져오기 <- ???
